/* tslint:disable */
/* eslint-disable */
/**
 * PlanRide.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LocationViewModel,
    LocationViewModelFromJSON,
    LocationViewModelFromJSONTyped,
    LocationViewModelToJSON,
} from './LocationViewModel';

/**
 * 
 * @export
 * @interface AvaliableOffersModel
 */
export interface AvaliableOffersModel {
    /**
     * 
     * @type {string}
     * @memberof AvaliableOffersModel
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof AvaliableOffersModel
     */
    numberOfSeats: number;
    /**
     * 
     * @type {number}
     * @memberof AvaliableOffersModel
     */
    id: number;
    /**
     * 
     * @type {LocationViewModel}
     * @memberof AvaliableOffersModel
     */
    destination: LocationViewModel;
    /**
     * 
     * @type {LocationViewModel}
     * @memberof AvaliableOffersModel
     */
    departure: LocationViewModel;
    /**
     * 
     * @type {Date}
     * @memberof AvaliableOffersModel
     */
    departureOffset: Date;
}

export function AvaliableOffersModelFromJSON(json: any): AvaliableOffersModel {
    return AvaliableOffersModelFromJSONTyped(json, false);
}

export function AvaliableOffersModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvaliableOffersModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['description'],
        'numberOfSeats': json['numberOfSeats'],
        'id': json['id'],
        'destination': LocationViewModelFromJSON(json['destination']),
        'departure': LocationViewModelFromJSON(json['departure']),
        'departureOffset': (new Date(json['departureOffset'])),
    };
}

export function AvaliableOffersModelToJSON(value?: AvaliableOffersModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'numberOfSeats': value.numberOfSeats,
        'id': value.id,
        'destination': LocationViewModelToJSON(value.destination),
        'departure': LocationViewModelToJSON(value.departure),
        'departureOffset': (value.departureOffset.toISOString()),
    };
}

