/* tslint:disable */
/* eslint-disable */
/**
 * PlanRide.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CountryViewModel
 */
export interface CountryViewModel {
    /**
     * 
     * @type {string}
     * @memberof CountryViewModel
     */
    countryCode: string;
    /**
     * 
     * @type {string}
     * @memberof CountryViewModel
     */
    name: string;
}

export function CountryViewModelFromJSON(json: any): CountryViewModel {
    return CountryViewModelFromJSONTyped(json, false);
}

export function CountryViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountryViewModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'countryCode': json['countryCode'],
        'name': json['name'],
    };
}

export function CountryViewModelToJSON(value?: CountryViewModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'countryCode': value.countryCode,
        'name': value.name,
    };
}

