/* tslint:disable */
/* eslint-disable */
/**
 * PlanRide.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTransportationRequestViewModel
 */
export interface CreateTransportationRequestViewModel {
    /**
     * 
     * @type {number}
     * @memberof CreateTransportationRequestViewModel
     */
    departureId: number;
    /**
     * 
     * @type {number}
     * @memberof CreateTransportationRequestViewModel
     */
    destinationId: number;
    /**
     * 
     * @type {Date}
     * @memberof CreateTransportationRequestViewModel
     */
    departureUTC: Date;
    /**
     * 
     * @type {number}
     * @memberof CreateTransportationRequestViewModel
     */
    numberOfPeople: number;
    /**
     * 
     * @type {number}
     * @memberof CreateTransportationRequestViewModel
     */
    numberOfPets: number;
}

export function CreateTransportationRequestViewModelFromJSON(json: any): CreateTransportationRequestViewModel {
    return CreateTransportationRequestViewModelFromJSONTyped(json, false);
}

export function CreateTransportationRequestViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTransportationRequestViewModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'departureId': json['departureId'],
        'destinationId': json['destinationId'],
        'departureUTC': (new Date(json['departureUTC'])),
        'numberOfPeople': json['numberOfPeople'],
        'numberOfPets': json['numberOfPets'],
    };
}

export function CreateTransportationRequestViewModelToJSON(value?: CreateTransportationRequestViewModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'departureId': value.departureId,
        'destinationId': value.destinationId,
        'departureUTC': (value.departureUTC.toISOString()),
        'numberOfPeople': value.numberOfPeople,
        'numberOfPets': value.numberOfPets,
    };
}

