/* tslint:disable */
/* eslint-disable */
/**
 * PlanRide.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTransportationRequestInputModel
 */
export interface CreateTransportationRequestInputModel {
    /**
     * 
     * @type {number}
     * @memberof CreateTransportationRequestInputModel
     */
    departureLocationId: number;
    /**
     * ISO-8601 date string
     * @type {Date}
     * @memberof CreateTransportationRequestInputModel
     */
    departureDate: Date;
    /**
     * 
     * @type {number}
     * @memberof CreateTransportationRequestInputModel
     */
    numberOfAdults: number;
    /**
     * 
     * @type {number}
     * @memberof CreateTransportationRequestInputModel
     */
    numberOfChildren: number;
    /**
     * 
     * @type {number}
     * @memberof CreateTransportationRequestInputModel
     */
    numberOfPets: number;
    /**
     * 
     * @type {string}
     * @memberof CreateTransportationRequestInputModel
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTransportationRequestInputModel
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTransportationRequestInputModel
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTransportationRequestInputModel
     */
    mobile: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTransportationRequestInputModel
     */
    comments?: string | null;
}

export function CreateTransportationRequestInputModelFromJSON(json: any): CreateTransportationRequestInputModel {
    return CreateTransportationRequestInputModelFromJSONTyped(json, false);
}

export function CreateTransportationRequestInputModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTransportationRequestInputModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'departureLocationId': json['departureLocationId'],
        'departureDate': (new Date(json['departureDate'])),
        'numberOfAdults': json['numberOfAdults'],
        'numberOfChildren': json['numberOfChildren'],
        'numberOfPets': json['numberOfPets'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'email': json['email'],
        'mobile': json['mobile'],
        'comments': !exists(json, 'comments') ? undefined : json['comments'],
    };
}

export function CreateTransportationRequestInputModelToJSON(value?: CreateTransportationRequestInputModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'departureLocationId': value.departureLocationId,
        'departureDate': (value.departureDate.toISOString().substr(0,10)),
        'numberOfAdults': value.numberOfAdults,
        'numberOfChildren': value.numberOfChildren,
        'numberOfPets': value.numberOfPets,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'email': value.email,
        'mobile': value.mobile,
        'comments': value.comments,
    };
}

