/* tslint:disable */
/* eslint-disable */
/**
 * PlanRide.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTransportationOfferInputModel
 */
export interface CreateTransportationOfferInputModel {
    /**
     * 
     * @type {number}
     * @memberof CreateTransportationOfferInputModel
     */
    departureLocationId: number;
    /**
     * ISO-8601 date string
     * @type {Date}
     * @memberof CreateTransportationOfferInputModel
     */
    departureDate: Date;
    /**
     * ISO-8601 time string (HH:mm)
     * @type {string}
     * @memberof CreateTransportationOfferInputModel
     */
    departureTime: string;
    /**
     * 
     * @type {number}
     * @memberof CreateTransportationOfferInputModel
     */
    destinationLocationId: number;
    /**
     * 
     * @type {number}
     * @memberof CreateTransportationOfferInputModel
     */
    numberOfSeats: number;
    /**
     * 
     * @type {string}
     * @memberof CreateTransportationOfferInputModel
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTransportationOfferInputModel
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTransportationOfferInputModel
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTransportationOfferInputModel
     */
    mobile: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTransportationOfferInputModel
     */
    comments?: string | null;
}

export function CreateTransportationOfferInputModelFromJSON(json: any): CreateTransportationOfferInputModel {
    return CreateTransportationOfferInputModelFromJSONTyped(json, false);
}

export function CreateTransportationOfferInputModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTransportationOfferInputModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'departureLocationId': json['departureLocationId'],
        'departureDate': (new Date(json['departureDate'])),
        'departureTime': json['departureTime'],
        'destinationLocationId': json['destinationLocationId'],
        'numberOfSeats': json['numberOfSeats'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'email': json['email'],
        'mobile': json['mobile'],
        'comments': !exists(json, 'comments') ? undefined : json['comments'],
    };
}

export function CreateTransportationOfferInputModelToJSON(value?: CreateTransportationOfferInputModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'departureLocationId': value.departureLocationId,
        'departureDate': (value.departureDate.toISOString().substr(0,10)),
        'departureTime': value.departureTime,
        'destinationLocationId': value.destinationLocationId,
        'numberOfSeats': value.numberOfSeats,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'email': value.email,
        'mobile': value.mobile,
        'comments': value.comments,
    };
}

