/* tslint:disable */
/* eslint-disable */
/**
 * PlanRide.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocationViewModel
 */
export interface LocationViewModel {
    /**
     * 
     * @type {number}
     * @memberof LocationViewModel
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof LocationViewModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof LocationViewModel
     */
    countryCode: string;
    /**
     * 
     * @type {number}
     * @memberof LocationViewModel
     */
    regionId: number;
    /**
     * 
     * @type {string}
     * @memberof LocationViewModel
     */
    regionName: string;
}

export function LocationViewModelFromJSON(json: any): LocationViewModel {
    return LocationViewModelFromJSONTyped(json, false);
}

export function LocationViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationViewModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'countryCode': json['countryCode'],
        'regionId': json['regionId'],
        'regionName': json['regionName'],
    };
}

export function LocationViewModelToJSON(value?: LocationViewModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'countryCode': value.countryCode,
        'regionId': value.regionId,
        'regionName': value.regionName,
    };
}

