/* tslint:disable */
/* eslint-disable */
/**
 * PlanRide.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ContactPersonViewModel,
    ContactPersonViewModelFromJSON,
    ContactPersonViewModelFromJSONTyped,
    ContactPersonViewModelToJSON,
} from './ContactPersonViewModel';
import {
    LocationViewModel,
    LocationViewModelFromJSON,
    LocationViewModelFromJSONTyped,
    LocationViewModelToJSON,
} from './LocationViewModel';

/**
 * 
 * @export
 * @interface OfferDetailsModel
 */
export interface OfferDetailsModel {
    /**
     * 
     * @type {string}
     * @memberof OfferDetailsModel
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof OfferDetailsModel
     */
    numberOfSeats: number;
    /**
     * 
     * @type {number}
     * @memberof OfferDetailsModel
     */
    id: number;
    /**
     * 
     * @type {LocationViewModel}
     * @memberof OfferDetailsModel
     */
    destination: LocationViewModel;
    /**
     * 
     * @type {LocationViewModel}
     * @memberof OfferDetailsModel
     */
    departure: LocationViewModel;
    /**
     * 
     * @type {Date}
     * @memberof OfferDetailsModel
     */
    departureOffset: Date;
    /**
     * 
     * @type {ContactPersonViewModel}
     * @memberof OfferDetailsModel
     */
    driver: ContactPersonViewModel;
}

export function OfferDetailsModelFromJSON(json: any): OfferDetailsModel {
    return OfferDetailsModelFromJSONTyped(json, false);
}

export function OfferDetailsModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): OfferDetailsModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['description'],
        'numberOfSeats': json['numberOfSeats'],
        'id': json['id'],
        'destination': LocationViewModelFromJSON(json['destination']),
        'departure': LocationViewModelFromJSON(json['departure']),
        'departureOffset': (new Date(json['departureOffset'])),
        'driver': ContactPersonViewModelFromJSON(json['driver']),
    };
}

export function OfferDetailsModelToJSON(value?: OfferDetailsModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'numberOfSeats': value.numberOfSeats,
        'id': value.id,
        'destination': LocationViewModelToJSON(value.destination),
        'departure': LocationViewModelToJSON(value.departure),
        'departureOffset': (value.departureOffset.toISOString()),
        'driver': ContactPersonViewModelToJSON(value.driver),
    };
}

