/* tslint:disable */
/* eslint-disable */
/**
 * PlanRide.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransportationOfferViewModel
 */
export interface TransportationOfferViewModel {
    /**
     * 
     * @type {string}
     * @memberof TransportationOfferViewModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TransportationOfferViewModel
     */
    departureCountryCode: string;
    /**
     * 
     * @type {number}
     * @memberof TransportationOfferViewModel
     */
    departureCityId: number;
    /**
     * 
     * @type {string}
     * @memberof TransportationOfferViewModel
     */
    departureCityName: string;
    /**
     * 
     * @type {string}
     * @memberof TransportationOfferViewModel
     */
    destinationCountryCode: string;
    /**
     * 
     * @type {number}
     * @memberof TransportationOfferViewModel
     */
    destinationCityId: number;
    /**
     * 
     * @type {string}
     * @memberof TransportationOfferViewModel
     */
    destinationCityName: string;
    /**
     * 
     * @type {number}
     * @memberof TransportationOfferViewModel
     */
    numberOfSeats: number;
    /**
     * ISO-8601 date string
     * @type {Date}
     * @memberof TransportationOfferViewModel
     */
    departureDate: Date;
    /**
     * ISO-8601 time string (HH:mm)
     * @type {string}
     * @memberof TransportationOfferViewModel
     */
    departureTime: string;
    /**
     * 
     * @type {Date}
     * @memberof TransportationOfferViewModel
     */
    dateCreated: Date;
}

export function TransportationOfferViewModelFromJSON(json: any): TransportationOfferViewModel {
    return TransportationOfferViewModelFromJSONTyped(json, false);
}

export function TransportationOfferViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransportationOfferViewModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'departureCountryCode': json['departureCountryCode'],
        'departureCityId': json['departureCityId'],
        'departureCityName': json['departureCityName'],
        'destinationCountryCode': json['destinationCountryCode'],
        'destinationCityId': json['destinationCityId'],
        'destinationCityName': json['destinationCityName'],
        'numberOfSeats': json['numberOfSeats'],
        'departureDate': (new Date(json['departureDate'])),
        'departureTime': json['departureTime'],
        'dateCreated': (new Date(json['dateCreated'])),
    };
}

export function TransportationOfferViewModelToJSON(value?: TransportationOfferViewModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'departureCountryCode': value.departureCountryCode,
        'departureCityId': value.departureCityId,
        'departureCityName': value.departureCityName,
        'destinationCountryCode': value.destinationCountryCode,
        'destinationCityId': value.destinationCityId,
        'destinationCityName': value.destinationCityName,
        'numberOfSeats': value.numberOfSeats,
        'departureDate': (value.departureDate.toISOString().substr(0,10)),
        'departureTime': value.departureTime,
        'dateCreated': (value.dateCreated.toISOString()),
    };
}

