/* tslint:disable */
/* eslint-disable */
/**
 * PlanRide.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransportationRequestDetailsViewModel
 */
export interface TransportationRequestDetailsViewModel {
    /**
     * 
     * @type {string}
     * @memberof TransportationRequestDetailsViewModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TransportationRequestDetailsViewModel
     */
    departureCountryCode: string;
    /**
     * 
     * @type {number}
     * @memberof TransportationRequestDetailsViewModel
     */
    departureCityId: number;
    /**
     * 
     * @type {string}
     * @memberof TransportationRequestDetailsViewModel
     */
    departureCityName: string;
    /**
     * 
     * @type {number}
     * @memberof TransportationRequestDetailsViewModel
     */
    numberOfPeople: number;
    /**
     * 
     * @type {boolean}
     * @memberof TransportationRequestDetailsViewModel
     */
    havePets: boolean;
    /**
     * ISO-8601 date string
     * @type {Date}
     * @memberof TransportationRequestDetailsViewModel
     */
    departureDate: Date;
    /**
     * 
     * @type {string}
     * @memberof TransportationRequestDetailsViewModel
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof TransportationRequestDetailsViewModel
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof TransportationRequestDetailsViewModel
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof TransportationRequestDetailsViewModel
     */
    mobile: string;
    /**
     * 
     * @type {string}
     * @memberof TransportationRequestDetailsViewModel
     */
    comments?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TransportationRequestDetailsViewModel
     */
    dateCreated: Date;
}

export function TransportationRequestDetailsViewModelFromJSON(json: any): TransportationRequestDetailsViewModel {
    return TransportationRequestDetailsViewModelFromJSONTyped(json, false);
}

export function TransportationRequestDetailsViewModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransportationRequestDetailsViewModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'departureCountryCode': json['departureCountryCode'],
        'departureCityId': json['departureCityId'],
        'departureCityName': json['departureCityName'],
        'numberOfPeople': json['numberOfPeople'],
        'havePets': json['havePets'],
        'departureDate': (new Date(json['departureDate'])),
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'email': json['email'],
        'mobile': json['mobile'],
        'comments': !exists(json, 'comments') ? undefined : json['comments'],
        'dateCreated': (new Date(json['dateCreated'])),
    };
}

export function TransportationRequestDetailsViewModelToJSON(value?: TransportationRequestDetailsViewModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'departureCountryCode': value.departureCountryCode,
        'departureCityId': value.departureCityId,
        'departureCityName': value.departureCityName,
        'numberOfPeople': value.numberOfPeople,
        'havePets': value.havePets,
        'departureDate': (value.departureDate.toISOString().substr(0,10)),
        'firstName': value.firstName,
        'lastName': value.lastName,
        'email': value.email,
        'mobile': value.mobile,
        'comments': value.comments,
        'dateCreated': (value.dateCreated.toISOString()),
    };
}

