/* tslint:disable */
/* eslint-disable */
/**
 * PlanRide.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    SignupInputModel,
    SignupInputModelFromJSON,
    SignupInputModelToJSON,
} from '../models';

export interface SignupRequest {
    signupInputModel?: SignupInputModel;
}

/**
 * 
 */
export class AccountApi extends runtime.BaseAPI {

    /**
     */
    async signupRaw(requestParameters: SignupRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/account/signup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignupInputModelToJSON(requestParameters.signupInputModel),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async signup(requestParameters: SignupRequest = {}, initOverrides?: RequestInit): Promise<void> {
        await this.signupRaw(requestParameters, initOverrides);
    }

}
